name: Deploy to AWS ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          ECR_REGISTRY=964832344816.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY=hostname
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Register new ECS task definition revision
        run: |
          aws ecs register-task-definition \
            --family inventory-management-system-task-definition \
            --network-mode awsvpc \
            --requires-compatibilities FARGATE \
            --cpu 512 \
            --memory 1024 \
            --execution-role-arn arn:aws:iam::964832344816:role/ecsTaskExecutionRole \
            --container-definitions file://container-definitions.json

      - name: Update ECS service to use latest task definition
        run: |
          NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition inventory-management-system-task-definition --query "taskDefinition.taskDefinitionArn" --output text)

          aws ecs update-service \
            --cluster inventory-management-system-ecs \
            --service inventory-management-system-task-definition-service-n4o02e6v \
            --task-definition $NEW_TASK_DEF_ARN

      - name: Deployment complete
        run: echo "🚀 Deployment to ECS completed successfully!"
